const ORANGE = '#FAA300';
const PINK = '#FF64CB';
const BACKGROUND = '#FFFFFF';
const PERSON_TINT = '#F4C95D';                   // soft-yellow stand-in body (used only in ?demo mode)
const PERSON_LIVE_TINT = 'rgba(250,163,0,0.32)'; // light warm tint over the real webcam person
const BURN_PINK = '#FF2E88';   // hot, "painful" pink used for the jellyfish burn
const BURN_RED = '#FF2A1E';    // red-hot core of the burn

const SAMPLE = 3;      // grid step used to sample the body outline (finer = fuller figure)
const SQUARE = SAMPLE; // drawn square size for silhouette cells (demo person / dissolve)

// --- Segmentation / tracking ---
const SEGMENT_INTERVAL = 80;         // ms between BodyPix calls
const SMOOTHING = 0.28;              // body-center + cell smoothing
const SEG_INTERNAL_RESOLUTION = 'high'; // 'medium' | 'high' | 'full' — raise to 'full' for max fidelity (slower)
const SEG_THRESHOLD = 0.55;          // lower => captures more of the body (fewer dropouts)

// --- Catch game tuning ---
const GAME_DIFFICULTY_RAMP = 80000; // ms to reach max difficulty (gentle)
const EMIT_INTERVAL_START = 950;    // ms between block bursts at the start
const EMIT_INTERVAL_END = 420;      // ms between block bursts at max difficulty
const BLOCK_SPEED_MIN = 0.85;       // slow — every block is catchable before it reaches the edge
const BLOCK_SPEED_MAX = 1.9;        // outward speed at max difficulty
const CATCH_RADIUS = 90;            // generous grab radius
const MAGNET_RADIUS = 180;          // nearby hand strongly attracts blocks so catching is reliable
const MAGNET_PULL = 0.55;           // strength of that magnet assist
const ABSORB_RADIUS = 26;           // distance to body center where a caught block is absorbed
const CAUGHT_PULL = 0.45;           // acceleration of a caught block back toward the body
const CAUGHT_FRICTION = 0.88;       // damping while reeling a caught block in

// --- Pink "jellyfish" escalation (triggered when a block escapes the frame) ---
const PINK_FLASH_MIN = 900;         // ms
const PINK_FLASH_MAX = 1400;        // ms
const MIN_PINK_SPAWN = 0.02;        // per-frame spawn chance right after the first escape
const MAX_PINK_SPAWN = 0.09;        // per-frame spawn chance after full escalation
const PINK_ESCALATION_DURATION = 16000;
const PINK_MAX = 16;                // cap so the jellyfish never flood the whole screen

// --- Dissolve end-phase (disabled): no more tiny squares scattering after 35s ---
const ENABLE_DISSOLVE = false;
const DISSOLVE_START = 35000;
const DISSOLVE_RAMP = 16000;
const DISSOLVE_BASE_RATE = 0.0015;
const DISSOLVE_MAX_RATE = 0.08;
const DISSOLVE_EXIT_MARGIN = 140;

// --- Demo mode (no camera): synthetic body + auto-controlled hands ---
const params = new URLSearchParams(location.search);
const DEMO = params.has('demo') && params.get('demo') !== '0';
const DEMO_MOUSE = params.get('demo') === 'mouse';
const DEMO_HAND_SPEED = 5.2; // capped so some fast blocks still escape

// --- Sizzle / shock sound (played when a pink jellyfish attaches to the body).
// sizzle.wav is generated by generate_sizzle.py; if it is missing we fall back
// to a fully synthesized electric sizzle so no external asset is required. ---
const touchSound = new Audio('sizzle.wav');
touchSound.preload = 'auto';
touchSound.volume = 0.8;
let audioContext = null;
function ensureAudio(){
  if(!audioContext){
    audioContext = new (window.AudioContext || window.webkitAudioContext)();
  }
  if(audioContext.state === 'suspended') audioContext.resume().catch(()=>{});
  return audioContext;
}
function playTouchSound(){
  if(touchSound.readyState >= 2){
    const clone = touchSound.cloneNode(); // allow overlapping sizzles
    clone.volume = touchSound.volume;
    clone.play().catch(()=>{});
    return;
  }
  synthSizzle();
}

// Fully synthesized electric sizzle (fallback when sizzle.wav is unavailable):
// crackly filtered noise + a descending "zap" tone.
function synthSizzle(){
  const ac = ensureAudio();
  const now = ac.currentTime;
  const dur = 0.45;

  const noise = ac.createBuffer(1, Math.floor(ac.sampleRate * dur), ac.sampleRate);
  const ch = noise.getChannelData(0);
  let prev = 0;
  for(let i = 0; i < ch.length; i++){
    const w = Math.random() * 2 - 1;
    const high = w - prev; prev = w;              // high-pass -> brighter fizz
    ch[i] = high * (Math.random() < 0.55 ? 1 : 0.25); // sparse crackle
  }
  const src = ac.createBufferSource();
  src.buffer = noise;
  const bp = ac.createBiquadFilter();
  bp.type = 'bandpass';
  bp.frequency.value = 3200;
  bp.Q.value = 0.8;
  const nGain = ac.createGain();
  nGain.gain.setValueAtTime(0.5, now);
  nGain.gain.exponentialRampToValueAtTime(0.001, now + dur);
  src.connect(bp).connect(nGain).connect(ac.destination);
  src.start(now);
  src.stop(now + dur);

  const osc = ac.createOscillator();
  const oGain = ac.createGain();
  osc.type = 'sawtooth';
  osc.frequency.setValueAtTime(430, now);
  osc.frequency.exponentialRampToValueAtTime(90, now + 0.2);
  oGain.gain.setValueAtTime(0.16, now);
  oGain.gain.exponentialRampToValueAtTime(0.001, now + 0.22);
  osc.connect(oGain).connect(ac.destination);
  osc.start(now);
  osc.stop(now + 0.22);
}
function playCatchSound(){
  const ac = ensureAudio();
  const osc = ac.createOscillator();
  const gain = ac.createGain();
  osc.type = 'triangle';
  osc.frequency.setValueAtTime(660, ac.currentTime);
  osc.frequency.exponentialRampToValueAtTime(990, ac.currentTime + 0.08);
  gain.gain.setValueAtTime(0.08, ac.currentTime);
  gain.gain.exponentialRampToValueAtTime(0.001, ac.currentTime + 0.1);
  osc.connect(gain).connect(ac.destination);
  osc.start();
  osc.stop(ac.currentTime + 0.1);
}

let video, canvas, ctx, net;
let width = 640, height = 480;

let silhouettePoints = [];
let silhouetteMap = new Map();
let bodyCenter = { x: width / 2, y: height / 2 };

let particles = [];        // flying / caught yellow blocks (the game pieces)
let dissolveParticles = [];
let pinks = [];
let burns = [];            // short-lived "burn" bursts where a jellyfish hit the body
let hands = [];            // current hand positions (wrists), in canvas/mirrored coords

let personDetected = false;
let gameStart = 0;
let lastEmit = 0;
let score = 0;
let escapes = 0;
let lastCatchAt = -9999;

let pinkEnabled = false;
let pinkPhaseStart = null;

// offscreen buffers for masking the webcam person onto the white background
let personCanvas, personCtx, maskCanvas, maskCtx, maskImageData;

// demo helpers
let demoBaseCells = [];
let demoHands = [];
const demoRemoved = new Set();
let mouse = { x: width / 2, y: height / 2, active: false };

/* ------------------------------------------------------------------ */
/* Setup                                                               */
/* ------------------------------------------------------------------ */

// Show a readable message on screen (creates the #hint box if it is missing).
function showMessage(msg){
  let el = document.getElementById('hint');
  if(!el){
    el = document.createElement('div');
    el.id = 'hint';
    document.body.appendChild(el);
  }
  el.style.position = 'fixed';
  el.style.left = '50%';
  el.style.bottom = '16px';
  el.style.transform = 'translateX(-50%)';
  el.style.maxWidth = '92vw';
  el.style.background = 'rgba(0,0,0,0.78)';
  el.style.color = '#fff';
  el.style.padding = '10px 16px';
  el.style.borderRadius = '10px';
  el.style.font = '14px Arial, sans-serif';
  el.style.direction = 'rtl';
  el.style.textAlign = 'center';
  el.style.zIndex = '20';
  el.textContent = msg;
}

function loadScript(src){
  return new Promise((resolve, reject) => {
    const s = document.createElement('script');
    s.src = src;
    s.onload = resolve;
    s.onerror = () => reject(new Error('נכשלה טעינת ' + src + ' (בדקי חיבור אינטרנט)'));
    document.head.appendChild(s);
  });
}

// Load TensorFlow.js + BodyPix from a CDN if index.html did not already include them.
async function ensureBodyPix(){
  if(typeof bodyPix !== 'undefined') return;
  await loadScript('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@2.4.0/dist/tf.min.js');
  await loadScript('https://cdn.jsdelivr.net/npm/@tensorflow-models/body-pix@2.2.0/dist/body-pix.min.js');
  if(typeof bodyPix === 'undefined') throw new Error('BodyPix לא נטען');
}

function setupCanvas(){
  canvas = document.getElementById('canvas');
  if(!canvas){
    canvas = document.createElement('canvas');
    canvas.id = 'canvas';
    document.body.appendChild(canvas);
  }
  canvas.width = width; canvas.height = height;
  canvas.style.width = '100%'; canvas.style.height = '100%';
  ctx = canvas.getContext('2d');
  ctx.imageSmoothingEnabled = false;
}

async function setupCamera(){
  video = document.getElementById('video');
  if(!video){
    video = document.createElement('video');
    video.id = 'video';
    video.style.display = 'none';
    document.body.appendChild(video);
  }
  video.playsInline = true;
  video.muted = true;
  if(!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia){
    throw new Error('גישה למצלמה חסומה — יש לפתוח דרך http://localhost או https (לא file://)');
  }
  const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'user' } });
  video.srcObject = stream;
  await video.play();
  width = video.videoWidth || width;
  height = video.videoHeight || height;
  video.width = width; video.height = height;
  video.style.display = 'none';
  if(canvas){ canvas.width = width; canvas.height = height; } // match real camera resolution
}

async function loadModel(){
  // ResNet50 gives noticeably better body segmentation; fall back to the
  // most accurate MobileNet config, then to defaults, on weaker devices.
  try{
    net = await bodyPix.load({ architecture: 'ResNet50', outputStride: 16, quantBytes: 2 });
  }catch(e){
    try{
      net = await bodyPix.load({ architecture: 'MobileNetV1', outputStride: 16, multiplier: 1.0, quantBytes: 2 });
    }catch(e2){
      net = await bodyPix.load();
    }
  }
}

/* ------------------------------------------------------------------ */
/* Silhouette sampling (live camera)                                   */
/* ------------------------------------------------------------------ */

function sampleSilhouette(segmentation){
  const data = segmentation.data;
  const newMap = new Map();
  silhouettePoints = [];
  const tempPoints = [];
  let minX = width, minY = height, maxX = 0, maxY = 0;

  for(let y = 0; y < height; y += SAMPLE){
    for(let x = 0; x < width; x += SAMPLE){
      const idx = y * width + x;
      if(data[idx] === 1){
        let neighbors = 0;
        for(let yy = -2; yy <= 2; yy += 2){
          for(let xx = -2; xx <= 2; xx += 2){
            const nx = x + xx, ny = y + yy;
            if(nx >= 0 && nx < width && ny >= 0 && ny < height && data[ny * width + nx] === 1) neighbors++;
          }
        }
        if(neighbors < 2) continue; // gentle denoise only; keep thin limbs/edges
        const gx = Math.floor(x / SAMPLE);
        const gy = Math.floor(y / SAMPLE);
        const cx = width - (gx * SAMPLE + SAMPLE / 2); // mirror X (selfie view)
        const cy = gy * SAMPLE + SAMPLE / 2;
        tempPoints.push({ gx, gy, cx, cy });
        if(cx < minX) minX = cx;
        if(cx > maxX) maxX = cx;
        if(cy < minY) minY = cy;
        if(cy > maxY) maxY = cy;
      }
    }
  }

  if(!tempPoints.length){ silhouetteMap = newMap; silhouettePoints = []; return; }

  const frameCenterX = (minX + maxX) / 2;
  const frameCenterY = (minY + maxY) / 2;
  bodyCenter.x += (frameCenterX - bodyCenter.x) * SMOOTHING;
  bodyCenter.y += (frameCenterY - bodyCenter.y) * SMOOTHING;

  for(const p of tempPoints){
    const relX = p.cx - bodyCenter.x;
    const relY = p.cy - bodyCenter.y;
    const relKeyX = Math.round(relX / SAMPLE);
    const relKeyY = Math.round(relY / SAMPLE);
    const relKey = relKeyX + "_" + relKeyY;
    const targetX = bodyCenter.x + relX;
    const targetY = bodyCenter.y + relY;
    const existing = silhouetteMap.get(relKey);

    silhouettePoints.push({ x: targetX, y: targetY, relKey, relX, relY, relKeyX, relKeyY });
    newMap.set(relKey, {
      relX, relY, relKey, relKeyX, relKeyY, targetX, targetY,
      dispX: existing ? existing.dispX : targetX,
      dispY: existing ? existing.dispY : targetY,
      hitStart: existing ? existing.hitStart : 0,
      hitDuration: existing ? existing.hitDuration : 0
    });
  }
  silhouetteMap = newMap;
}

function getHandsFromPoses(poses){
  const out = [];
  if(!poses) return out;
  for(const pose of poses){
    if(!pose.keypoints) continue;
    for(const kp of pose.keypoints){
      if((kp.part === 'leftWrist' || kp.part === 'rightWrist') && kp.score > 0.15){
        out.push({ x: width - kp.position.x, y: kp.position.y }); // mirror X to match the flipped view
      }
    }
  }
  return out;
}

/* ------------------------------------------------------------------ */
/* Person rendering (live camera) – show the real person, masked       */
/* ------------------------------------------------------------------ */

function ensurePersonBuffers(){
  if(!personCanvas){ personCanvas = document.createElement('canvas'); personCtx = personCanvas.getContext('2d'); }
  if(personCanvas.width !== width || personCanvas.height !== height){ personCanvas.width = width; personCanvas.height = height; }
  if(!maskCanvas){ maskCanvas = document.createElement('canvas'); maskCtx = maskCanvas.getContext('2d'); }
  if(maskCanvas.width !== width || maskCanvas.height !== height){
    maskCanvas.width = width; maskCanvas.height = height;
    maskImageData = maskCtx.createImageData(width, height);
  }
}

function updateMask(segmentation){
  ensurePersonBuffers();
  const d = segmentation.data;
  const px = maskImageData.data;
  for(let i = 0; i < d.length; i++){
    const o = i * 4;
    if(d[i] === 1){ px[o] = 255; px[o + 1] = 255; px[o + 2] = 255; px[o + 3] = 255; }
    else { px[o + 3] = 0; }
  }
  maskCtx.putImageData(maskImageData, 0, 0);
}

function drawPerson(){
  if(!video || video.readyState < 2 || !maskCanvas) return;
  ensurePersonBuffers();
  personCtx.clearRect(0, 0, width, height);
  personCtx.save();
  personCtx.scale(-1, 1);
  personCtx.translate(-width, 0);
  personCtx.drawImage(video, 0, 0, width, height);          // mirrored webcam
  personCtx.globalCompositeOperation = 'destination-in';
  personCtx.drawImage(maskCanvas, 0, 0);                     // keep only the person
  personCtx.restore();
  // light warm tint over the person so it reads a bit yellow (like the original piece)
  personCtx.globalCompositeOperation = 'source-atop';
  personCtx.fillStyle = PERSON_LIVE_TINT;
  personCtx.fillRect(0, 0, width, height);
  personCtx.globalCompositeOperation = 'source-over';
  ctx.drawImage(personCanvas, 0, 0);
}

/* ------------------------------------------------------------------ */
/* The yellow blocks (game pieces)                                     */
/* ------------------------------------------------------------------ */

function emitBlock(difficulty){
  if(!silhouettePoints.length) return;
  const p = silhouettePoints[Math.floor(Math.random() * silhouettePoints.length)];
  let dx = p.x - bodyCenter.x, dy = p.y - bodyCenter.y;
  let m = Math.hypot(dx, dy);
  let dirx, diry;
  if(m < 1){ const a = Math.random() * Math.PI * 2; dirx = Math.cos(a); diry = Math.sin(a); }
  else { dirx = dx / m; diry = dy / m; }
  // rotate direction slightly for a natural spread
  const spread = (Math.random() - 0.5) * 0.8;
  const ca = Math.cos(spread), sa = Math.sin(spread);
  const rx = dirx * ca - diry * sa;
  const ry = dirx * sa + diry * ca;
  const speed = BLOCK_SPEED_MIN + difficulty * (BLOCK_SPEED_MAX - BLOCK_SPEED_MIN) + Math.random() * 0.9;
  const size = 10 + Math.random() * 12;
  particles.push({
    x: p.x, y: p.y,
    vx: rx * speed, vy: ry * speed,
    size, state: 'flying', born: performance.now()
  });
}

function updateBlocks(dt, now){
  const margin = 4;
  for(let i = particles.length - 1; i >= 0; i--){
    const b = particles[i];

    if(b.state === 'flying'){
      for(const h of hands){
        if(Math.hypot(h.x - b.x, h.y - b.y) < CATCH_RADIUS + b.size / 2){
          b.state = 'caught';
          lastCatchAt = now;
          playCatchSound();
          break;
        }
      }
      if(b.state === 'flying'){
        // magnet assist: a nearby hand gently pulls the block toward it so
        // catching feels intuitive instead of requiring a pixel-perfect touch.
        let nearHand = null, nearDist = MAGNET_RADIUS;
        for(const h of hands){
          const d = Math.hypot(h.x - b.x, h.y - b.y);
          if(d < nearDist){ nearDist = d; nearHand = h; }
        }
        if(nearHand){
          const dx = nearHand.x - b.x, dy = nearHand.y - b.y, m = Math.hypot(dx, dy) || 1;
          const strength = MAGNET_PULL * (1 - nearDist / MAGNET_RADIUS);
          b.vx += (dx / m) * strength;
          b.vy += (dy / m) * strength;
        }
        b.x += b.vx * dt / 16;
        b.y += b.vy * dt / 16;
        if(b.x < -margin || b.x > width + margin || b.y < -margin || b.y > height + margin){
          particles.splice(i, 1);
          onBlockEscaped(now);
          continue;
        }
      }
    }

    if(b.state === 'caught'){
      const dx = bodyCenter.x - b.x, dy = bodyCenter.y - b.y;
      const d = Math.hypot(dx, dy) || 1;
      b.vx += (dx / d) * CAUGHT_PULL;
      b.vy += (dy / d) * CAUGHT_PULL;
      b.vx *= CAUGHT_FRICTION;
      b.vy *= CAUGHT_FRICTION;
      b.x += b.vx * dt / 16;
      b.y += b.vy * dt / 16;
      if(d < ABSORB_RADIUS){
        particles.splice(i, 1);
        score++;
        updateScoreLabel();
      }
    }
  }
}

function onBlockEscaped(now){
  escapes++;
  if(!pinkEnabled){
    pinkEnabled = true;
    pinkPhaseStart = now;
  }
  // every escape sends a small burst of jellyfish (capped so they never flood)
  if(pinkEnabled){
    const burst = 1 + Math.min(2, Math.floor(escapes / 6));
    for(let k = 0; k < burst && pinks.length < PINK_MAX; k++) spawnPink();
  }
}

function drawBlocks(){
  // tether: show caught blocks being reeled back toward the body
  ctx.save();
  ctx.strokeStyle = 'rgba(250,163,0,0.35)';
  ctx.lineWidth = 2;
  for(const b of particles){
    if(b.state === 'caught'){
      ctx.beginPath();
      ctx.moveTo(b.x, b.y);
      ctx.lineTo(bodyCenter.x, bodyCenter.y);
      ctx.stroke();
    }
  }
  ctx.restore();

  ctx.save();
  for(const b of particles){
    if(b.state === 'caught'){
      // caught blocks get a subtle outline so the "grab" reads clearly
      ctx.fillStyle = ORANGE;
      ctx.fillRect(b.x - b.size / 2, b.y - b.size / 2, b.size, b.size);
      ctx.strokeStyle = 'rgba(255,120,0,0.9)';
      ctx.lineWidth = 2;
      ctx.strokeRect(b.x - b.size / 2 - 1, b.y - b.size / 2 - 1, b.size + 2, b.size + 2);
    } else {
      ctx.fillStyle = ORANGE;
      ctx.fillRect(b.x - b.size / 2, b.y - b.size / 2, b.size, b.size);
    }
  }
  ctx.restore();
}

/* ------------------------------------------------------------------ */
/* Dissolve end-phase                                                  */
/* ------------------------------------------------------------------ */

function detachSilhouetteCell(cell, now){
  silhouetteMap.delete(cell.relKey);
  silhouettePoints = silhouettePoints.filter(p => p.relKey !== cell.relKey);
  if(DEMO) demoRemoved.add(cell.relKey);

  const edge = Math.floor(Math.random() * 4);
  let destX, destY;
  if(edge === 0){ destX = Math.random() * width; destY = -80; }
  else if(edge === 1){ destX = width + 80; destY = Math.random() * height; }
  else if(edge === 2){ destX = Math.random() * width; destY = height + 80; }
  else { destX = -80; destY = Math.random() * height; }

  const dx = destX - cell.dispX, dy = destY - cell.dispY;
  const distance = Math.hypot(dx, dy) || 1;
  const speed = 2.4 + Math.random() * 1.6;
  const startX = cell.dispX, startY = cell.dispY;
  const removalX = destX > width / 2 ? width + DISSOLVE_EXIT_MARGIN : -DISSOLVE_EXIT_MARGIN;
  const removalY = destY > height / 2 ? height + DISSOLVE_EXIT_MARGIN : -DISSOLVE_EXIT_MARGIN;
  const offscreenDist = Math.hypot(removalX - startX, removalY - startY) || distance;

  dissolveParticles.push({
    x: startX, y: startY,
    vx: (dx / distance) * speed + (Math.random() - 0.5) * 0.35,
    vy: (dy / distance) * speed + (Math.random() - 0.5) * 0.35,
    size: SQUARE + Math.random() * SQUARE,
    alpha: 1, fading: false,
    startX, startY, offscreenDist, born: now
  });
}

function updateDissolveParticles(dt){
  for(let i = dissolveParticles.length - 1; i >= 0; i--){
    const p = dissolveParticles[i];
    p.vx *= 0.993; p.vy *= 0.993;
    p.vy -= 0.002 * dt / 16;
    p.x += p.vx * dt / 16;
    p.y += p.vy * dt / 16;

    const relKeyX = Math.round((p.x - bodyCenter.x) / SAMPLE);
    const relKeyY = Math.round((p.y - bodyCenter.y) / SAMPLE);
    if(!p.fading && !silhouetteMap.has(`${relKeyX}_${relKeyY}`)) p.fading = true;
    if(p.fading){
      const traveled = Math.hypot(p.x - p.startX, p.y - p.startY);
      p.alpha = Math.max(0, 1 - (traveled / (p.offscreenDist || 1)));
    }
    if(p.x < -DISSOLVE_EXIT_MARGIN || p.x > width + DISSOLVE_EXIT_MARGIN || p.y < -DISSOLVE_EXIT_MARGIN || p.y > height + DISSOLVE_EXIT_MARGIN){
      dissolveParticles.splice(i, 1);
    }
  }
}

function updateDissolve(now, dt){
  if(!ENABLE_DISSOLVE) return; // the "shatter into tiny squares" phase is turned off
  if(!pinkPhaseStart || !silhouettePoints.length){ updateDissolveParticles(dt); return; }
  const elapsed = now - pinkPhaseStart;
  if(elapsed > DISSOLVE_START){
    const progress = Math.min(1, (elapsed - DISSOLVE_START) / DISSOLVE_RAMP);
    const detachChance = DISSOLVE_BASE_RATE + progress * DISSOLVE_MAX_RATE;
    for(const cell of Array.from(silhouetteMap.values())){
      if(Math.random() < detachChance * dt / 16) detachSilhouetteCell(cell, now);
    }
  }
  updateDissolveParticles(dt);
}

function drawDissolveParticles(){
  ctx.save();
  ctx.fillStyle = ORANGE;
  for(const p of dissolveParticles){
    ctx.globalAlpha = p.alpha;
    ctx.fillRect(p.x - p.size / 2, p.y - p.size / 2, p.size, p.size);
  }
  ctx.restore();
}

/* ------------------------------------------------------------------ */
/* Pink jellyfish                                                      */
/* ------------------------------------------------------------------ */

function spawnPink(){
  const edge = Math.floor(Math.random() * 4);
  let x, y;
  if(edge === 0){ x = Math.random() * width; y = -20; }
  else if(edge === 1){ x = width + 20; y = Math.random() * height; }
  else if(edge === 2){ x = Math.random() * width; y = height + 20; }
  else { x = -20; y = Math.random() * height; }
  let target = { x: width / 2, y: height / 2 };
  if(silhouettePoints.length) target = silhouettePoints[Math.floor(Math.random() * silhouettePoints.length)];
  const dx = target.x - x, dy = target.y - y;
  const mag = Math.hypot(dx, dy) || 1;
  const speed = 0.7 + Math.random() * 0.75;
  pinks.push({
    x, y, vx: dx / mag * speed, vy: dy / mag * speed,
    targetX: target.x, targetY: target.y,
    r: 10 + Math.random() * 16, born: performance.now(),
    attached: false, attachKey: null,
    attachOffsetX: undefined, attachOffsetY: undefined,
    attachStart: 0, attachedTime: 0, attachDuration: 0
  });
}

function updatePinks(dt){
  const now = performance.now();
  for(let i = pinks.length - 1; i >= 0; i--){
    const c = pinks[i];
    if(c.attached){
      if(c.attachKey && silhouetteMap.has(c.attachKey)){
        const cell = silhouetteMap.get(c.attachKey);
        c.x = cell.dispX; c.y = cell.dispY;
      } else if(c.attachOffsetX !== undefined){
        c.x = bodyCenter.x + c.attachOffsetX;
        c.y = bodyCenter.y + c.attachOffsetY;
      }
      c.attachedTime = now - c.attachStart;
      if(c.attachedTime > c.attachDuration) pinks.splice(i, 1);
      continue;
    }
    if(silhouettePoints.length){
      if(!c.targetX || Math.random() < 0.005){
        const target = silhouettePoints[Math.floor(Math.random() * silhouettePoints.length)];
        c.targetX = target.x; c.targetY = target.y;
      }
      const dx = c.targetX - c.x, dy = c.targetY - c.y;
      const mag = Math.hypot(dx, dy) || 1;
      c.vx += (dx / mag) * 0.045;
      c.vy += (dy / mag) * 0.045;
      c.vx += (Math.random() - 0.5) * 0.06;
      c.vy += (Math.random() - 0.5) * 0.06;
      if(Math.hypot(c.vx, c.vy) > 3){ c.vx *= 0.92; c.vy *= 0.92; }
    }
    c.x += c.vx * dt / 16;
    c.y += c.vy * dt / 16;
    if(c.x < -60 || c.x > width + 60 || c.y < -60 || c.y > height + 60) pinks.splice(i, 1);
    else checkPinkCollision(c);
  }
}

function checkPinkCollision(circle){
  if(circle.attached) return;
  const now = performance.now();
  const candidates = [];
  for(const p of silhouettePoints){
    const d = Math.hypot(p.x - circle.x, p.y - circle.y);
    if(d < circle.r + SAMPLE * 0.9) candidates.push(p);
  }
  if(!candidates.length) return;
  const p = candidates[Math.floor(Math.random() * candidates.length)];
  const cell = silhouetteMap.get(p.relKey);
  if(!cell) return;

  circle.attached = true;
  circle.attachKey = p.relKey;
  circle.attachOffsetX = cell.relX;
  circle.attachOffsetY = cell.relY;
  circle.attachStart = now;
  circle.attachDuration = PINK_FLASH_MIN + Math.random() * (PINK_FLASH_MAX - PINK_FLASH_MIN);
  circle.vx = 0; circle.vy = 0;
  playTouchSound();

  // a glowing "burn" burst at the point of contact
  burns.push({ x: cell.dispX, y: cell.dispY, born: now, duration: 620, maxR: 30 + Math.random() * 22 });

  const spread = 5; // wider, angrier scorch across the body
  for(let sy = -spread; sy <= spread; sy++){
    for(let sx = -spread; sx <= spread; sx++){
      const neighbor = silhouetteMap.get((cell.relKeyX + sx) + "_" + (cell.relKeyY + sy));
      if(neighbor){
        const dist = Math.hypot(sx, sy);
        if(dist <= spread + 0.2){
          const intensity = 1 - (dist / (spread + 0.2));
          neighbor.hitStart = now;
          neighbor.hitDuration = PINK_FLASH_MIN + intensity * (PINK_FLASH_MAX - PINK_FLASH_MIN);
          neighbor.hitIntensity = intensity;
        }
      }
    }
  }
}

function drawPinks(){
  ctx.save();
  for(const c of pinks){
    if(c.attached){
      // attached jellyfish glow hot, as if searing the body
      ctx.shadowColor = BURN_PINK;
      ctx.shadowBlur = 18;
      ctx.fillStyle = BURN_PINK;
    } else {
      ctx.shadowBlur = 0;
      ctx.fillStyle = PINK;
    }
    ctx.beginPath();
    ctx.arc(c.x, c.y, c.r, 0, Math.PI * 2);
    ctx.fill();
  }
  ctx.restore();
}

/* ------------------------------------------------------------------ */
/* Silhouette animation + hand indicator + HUD                         */
/* ------------------------------------------------------------------ */

function animateSilhouette(){
  for(const obj of silhouetteMap.values()){
    obj.dispX += (obj.targetX - obj.dispX) * SMOOTHING;
    obj.dispY += (obj.targetY - obj.dispY) * SMOOTHING;
  }
}

// In demo mode the person is drawn as a pixelated grey stand-in (no webcam).
// The pink hit-flash from the jellyfish is shown on top in both modes.
function drawPersonHits(){
  const now = performance.now();
  ctx.save();
  for(const obj of silhouetteMap.values()){
    if(obj.hitStart && obj.hitDuration){
      const t = (now - obj.hitStart) / obj.hitDuration;
      if(t < 1){
        const fade = 1 - Math.min(1, t);
        const intensity = obj.hitIntensity || 0.5;
        // hot-pink scorch that spills a bit beyond the cell...
        const s = SQUARE * (1.4 + intensity);
        ctx.globalAlpha = fade;
        ctx.fillStyle = BURN_PINK;
        ctx.fillRect(obj.dispX - s / 2, obj.dispY - s / 2, s, s);
        // ...with a red-hot core near the point of impact
        if(intensity > 0.6){
          ctx.globalAlpha = fade * intensity;
          ctx.fillStyle = BURN_RED;
          ctx.fillRect(obj.dispX - SQUARE / 2, obj.dispY - SQUARE / 2, SQUARE, SQUARE);
        }
      }
    }
  }
  ctx.restore();
}

// Expanding, glowing burn burst at each jellyfish contact point.
function updateBurns(now){
  for(let i = burns.length - 1; i >= 0; i--){
    if(now - burns[i].born > burns[i].duration) burns.splice(i, 1);
  }
}

function drawBurns(now){
  ctx.save();
  for(const b of burns){
    const t = (now - b.born) / b.duration;
    if(t >= 1) continue;
    const fade = 1 - t;
    const r = b.maxR * (0.3 + t * 0.95);
    const g = ctx.createRadialGradient(b.x, b.y, 1, b.x, b.y, r);
    g.addColorStop(0, `rgba(255,255,255,${0.9 * fade})`);
    g.addColorStop(0.30, `rgba(255,42,30,${0.85 * fade})`);   // red-hot
    g.addColorStop(0.65, `rgba(255,46,136,${0.55 * fade})`);  // hot pink
    g.addColorStop(1, 'rgba(255,46,136,0)');
    ctx.fillStyle = g;
    ctx.beginPath();
    ctx.arc(b.x, b.y, r, 0, Math.PI * 2);
    ctx.fill();
    // sharp shock ring travelling outward
    ctx.globalAlpha = fade;
    ctx.lineWidth = 2;
    ctx.strokeStyle = BURN_PINK;
    ctx.beginPath();
    ctx.arc(b.x, b.y, r * 1.12, 0, Math.PI * 2);
    ctx.stroke();
    ctx.globalAlpha = 1;
  }
  ctx.restore();
}

function drawDemoPerson(){
  ctx.save();
  ctx.fillStyle = PERSON_TINT;
  for(const obj of silhouetteMap.values()){
    ctx.fillRect(obj.dispX - SQUARE / 2, obj.dispY - SQUARE / 2, SQUARE, SQUARE);
  }
  ctx.restore();
}

function drawHands(){
  const flash = Math.max(0, 1 - (performance.now() - lastCatchAt) / 200);
  ctx.save();
  for(const h of hands){
    ctx.lineWidth = 2 + flash * 3;
    ctx.strokeStyle = `rgba(250,163,0,${0.5 + flash * 0.4})`;
    ctx.beginPath();
    ctx.arc(h.x, h.y, CATCH_RADIUS, 0, Math.PI * 2);
    ctx.stroke();
    if(flash > 0){
      ctx.globalAlpha = flash * 0.25;
      ctx.fillStyle = ORANGE;
      ctx.fill();
      ctx.globalAlpha = 1;
    }
  }
  ctx.restore();
}

function updateScoreLabel(){
  const el = document.getElementById('score');
  if(el) el.textContent = String(score);
}

/* ------------------------------------------------------------------ */
/* Presence / game lifecycle                                           */
/* ------------------------------------------------------------------ */

function startGame(now){
  particles = [];
  dissolveParticles = [];
  pinks = [];
  burns = [];
  pinkEnabled = false;
  pinkPhaseStart = null;
  score = 0;
  escapes = 0;
  demoRemoved.clear();
  gameStart = now;
  lastEmit = now;
  updateScoreLabel();
}

function resetScene(){
  silhouettePoints = [];
  silhouetteMap.clear();
  particles = [];
  dissolveParticles = [];
  pinks = [];
  burns = [];
  pinkEnabled = false;
  pinkPhaseStart = null;
}

function updatePersonPresence(segmentation){
  const data = segmentation.data;
  let areaCount = 0, minX = width, maxX = 0, minY = height, maxY = 0;
  for(let y = 0; y < height; y += 4){
    for(let x = 0; x < width; x += 4){
      if(data[y * width + x] === 1){
        areaCount++;
        if(x < minX) minX = x; if(x > maxX) maxX = x;
        if(y < minY) minY = y; if(y > maxY) maxY = y;
      }
    }
  }
  const areaRatio = areaCount / ((width * height) / 16);
  const boxWidth = maxX - minX, boxHeight = maxY - minY;
  const isLargeEnough = areaRatio > 0.015 && boxWidth > width * 0.18 && boxHeight > height * 0.25;

  if(isLargeEnough){
    if(!personDetected){ personDetected = true; startGame(performance.now()); }
    updateMask(segmentation);
    sampleSilhouette(segmentation);
  } else if(personDetected){
    personDetected = false;
    resetScene();
  }
}

/* ------------------------------------------------------------------ */
/* Demo mode: synthetic humanoid + auto hands                          */
/* ------------------------------------------------------------------ */

function buildDemoBaseCells(){
  demoBaseCells = [];
  const shapes = [
    { cx: 0,   cy: -120, rx: 30, ry: 36 }, // head
    { cx: 0,   cy: -12,  rx: 46, ry: 78 }, // torso
    { cx: -58, cy: -18,  rx: 15, ry: 58 }, // left arm
    { cx: 58,  cy: -18,  rx: 15, ry: 58 }, // right arm
    { cx: -22, cy: 118,  rx: 17, ry: 70 }, // left leg
    { cx: 22,  cy: 118,  rx: 17, ry: 70 }  // right leg
  ];
  const inside = (x, y) => shapes.some(s => {
    const dx = (x - s.cx) / s.rx, dy = (y - s.cy) / s.ry;
    return dx * dx + dy * dy <= 1;
  });
  for(let y = -170; y <= 200; y += SAMPLE){
    for(let x = -90; x <= 90; x += SAMPLE){
      if(inside(x, y)){
        const relKeyX = Math.round(x / SAMPLE);
        const relKeyY = Math.round(y / SAMPLE);
        demoBaseCells.push({ relX: x, relY: y, relKeyX, relKeyY, relKey: relKeyX + "_" + relKeyY });
      }
    }
  }
}

function updateDemoSilhouette(now){
  bodyCenter.x = width / 2 + Math.sin(now * 0.0007) * 20;
  bodyCenter.y = height / 2 + Math.sin(now * 0.001) * 10;
  const newMap = new Map();
  silhouettePoints = [];
  for(const c of demoBaseCells){
    if(demoRemoved.has(c.relKey)) continue;
    const targetX = bodyCenter.x + c.relX;
    const targetY = bodyCenter.y + c.relY;
    const existing = silhouetteMap.get(c.relKey);
    silhouettePoints.push({ x: targetX, y: targetY, relKey: c.relKey, relX: c.relX, relY: c.relY, relKeyX: c.relKeyX, relKeyY: c.relKeyY });
    newMap.set(c.relKey, {
      relX: c.relX, relY: c.relY, relKey: c.relKey, relKeyX: c.relKeyX, relKeyY: c.relKeyY,
      targetX, targetY,
      dispX: existing ? existing.dispX : targetX,
      dispY: existing ? existing.dispY : targetY,
      hitStart: existing ? existing.hitStart : 0,
      hitDuration: existing ? existing.hitDuration : 0
    });
  }
  silhouetteMap = newMap;
}

function updateDemoHands(dt){
  if(DEMO_MOUSE){
    hands = mouse.active ? [{ x: mouse.x, y: mouse.y }] : [];
    return;
  }
  for(const h of demoHands){
    let best = null, bd = Infinity;
    for(const b of particles){
      if(b.state !== 'flying') continue;
      const d = Math.hypot(b.x - h.x, b.y - h.y);
      if(d < bd){ bd = d; best = b; }
    }
    if(best){
      const dx = best.x - h.x, dy = best.y - h.y, m = Math.hypot(dx, dy) || 1;
      h.x += (dx / m) * DEMO_HAND_SPEED * dt / 16;
      h.y += (dy / m) * DEMO_HAND_SPEED * dt / 16;
    } else {
      h.x += (h.homeX - h.x) * 0.05;
      h.y += (h.homeY - h.y) * 0.05;
    }
  }
  hands = demoHands.map(h => ({ x: h.x, y: h.y }));
}

/* ------------------------------------------------------------------ */
/* Main loop                                                           */
/* ------------------------------------------------------------------ */

let last = performance.now();
function frame(){
  const now = performance.now();
  const dt = Math.min(48, now - last); last = now;

  ctx.fillStyle = BACKGROUND;
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  if(DEMO) updateDemoSilhouette(now);

  if(personDetected){
    animateSilhouette();

    if(DEMO) drawDemoPerson();
    else drawPerson();
    drawPersonHits();

    const difficulty = Math.min(1, (now - gameStart) / GAME_DIFFICULTY_RAMP);
    const emitInterval = EMIT_INTERVAL_START + (EMIT_INTERVAL_END - EMIT_INTERVAL_START) * difficulty;
    if(now - lastEmit > emitInterval){
      lastEmit = now;
      const count = 1 + Math.floor(difficulty * 1.0 + Math.random() * 0.4);
      for(let k = 0; k < count; k++) emitBlock(difficulty);
    }

    if(DEMO) updateDemoHands(dt);
    updateBlocks(dt, now);
    drawBlocks();

    updateDissolve(now, dt);
    drawDissolveParticles();

    if(pinkEnabled && pinkPhaseStart){
      const phase = Math.min(1, (now - pinkPhaseStart) / PINK_ESCALATION_DURATION);
      const spawnChance = MIN_PINK_SPAWN + (MAX_PINK_SPAWN - MIN_PINK_SPAWN) * phase;
      if(pinks.length < PINK_MAX && Math.random() < spawnChance) spawnPink();
    }
    updatePinks(dt);
    drawPinks();
    updateBurns(now);
    drawBurns(now);

    drawHands();
  }

  requestAnimationFrame(frame);
}

async function segmentationLoop(){
  while(true){
    if(net && video && video.readyState >= 2){
      try{
        const segmentation = await net.segmentPerson(video, {
          internalResolution: SEG_INTERNAL_RESOLUTION,
          segmentationThreshold: SEG_THRESHOLD,
          maxDetections: 1,
          scoreThreshold: 0.3,
          nmsRadius: 20
        });
        hands = getHandsFromPoses(segmentation.allPoses);
        updatePersonPresence(segmentation);
      }catch(e){ console.error('segmentation error', e); }
    }
    await new Promise(r => setTimeout(r, SEGMENT_INTERVAL));
  }
}

/* ------------------------------------------------------------------ */
/* Init                                                                */
/* ------------------------------------------------------------------ */

(async function init(){
  if(DEMO){
    width = 640; height = 480;
    setupCanvas();
    buildDemoBaseCells();
    demoHands = [
      { x: width / 2 - 130, y: height / 2, homeX: width / 2 - 130, homeY: height / 2 },
      { x: width / 2 + 130, y: height / 2, homeX: width / 2 + 130, homeY: height / 2 }
    ];
    personDetected = true;
    startGame(performance.now());
    if(DEMO_MOUSE){
      window.addEventListener('mousemove', e => {
        const r = canvas.getBoundingClientRect();
        mouse.x = (e.clientX - r.left) * (width / r.width);
        mouse.y = (e.clientY - r.top) * (height / r.height);
        mouse.active = true;
      });
    }
    // unlock audio on first interaction (browser autoplay policy)
    window.addEventListener('pointerdown', ensureAudio, { once: true });
    window.addEventListener('keydown', ensureAudio, { once: true });
    frame();
    return;
  }

  try{
    setupCanvas();
    frame(); // start rendering (blank white) so the page is responsive while the camera/model load
    window.addEventListener('pointerdown', ensureAudio, { once: true });
    await setupCamera();
    await ensureBodyPix();
    await loadModel();
    segmentationLoop();
  }catch(e){
    console.error(e);
    showMessage('לא ניתן להפעיל: ' + (e && e.message ? e.message : e) +
      ' — ודאי שהעמוד רץ דרך http://localhost:8000 (לא file://) ושאישרת גישה למצלמה. לבדיקה ללא מצלמה הוסיפי ?demo=1 לכתובת.');
  }
})();

window.addEventListener('resize', () => {
  if(canvas){ canvas.width = width; canvas.height = height; }
});
